### ISSUE TITLE
Fix option doesn't appear when this plugin is included

### ISSUE THREAD

**Issue by davidpshea** [justlep/eslint-plugin-log-filenames#4]
2 projects, identical, one with the plugin, one without.
Without, I get this,
"12 errors and 0 warnings potentially fixable with the `--fix` option."

With the plugin I get this,
"12 problems (12 errors, 0 warnings)"

This is using vite/react/typescript starter application, adding eslint prettier, and making some whitespace formatting changes.

**Comment by justlep** [comment]
Hi David, thanks for pointing out the problem.
Looks like the [developer guide for plugins](https://eslint.org/docs/developer-guide/working-with-plugins) has changed slightly since my last view. 

I just fixed the issue in v1.0.6.

Cheers
